# Generated by Django 2.2 on 2019-04-04 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_finish',
            field=models.DateField(default=datetime.datetime(2019, 4, 4, 22, 29, 15, 688652)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_init',
            field=models.DateField(default=datetime.datetime(2019, 4, 4, 22, 29, 15, 688606)),
        ),
    ]
