# Generated by Django 2.2 on 2019-04-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20190404_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_finish',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_init',
            field=models.DateField(),
        ),
    ]
