# Generated by Django 2.2 on 2019-04-11 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_email'),
        ('task', '0003_auto_20190405_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='id_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
            preserve_default=False,
        ),
    ]
