# Generated by Django 2.2 on 2019-04-11 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_email'),
        ('task', '0004_task_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
